### PR TITLE
Update the date syntax to use gnu date

### PR DESCRIPTION
**Pull request by halcyondaz**

### CODE REVIEW

**Comment by mikaelvesavuori** [comment]
Hey! Thanks for this.

Since this is at least 2 different changes, I'd want this to be a separate pull request from the new feature being added.

For the date, I'm not getting that variant to work correctly on MacOS — this is the same I tried in my own work. Unfortunately, it gives too big values, i.e.

```
Days since the last commit: 19605
```
 
Is there an issue with the current formatting when run on your system, which I suspect is some Linux variant?

**Comment by halcyondaz** [comment]
Mac/BSD uses a non standard date variant, this fix makes it run with 90% of the linux distros...
We should do a switch then that uses the Mac/BSD version on Mac/BSD and the Linux version on linux.

lemme try to find something that does that

**Comment by halcyondaz** [comment]
https://github.com/travis-ci/travis-build/blob/061cd364c38a07c8908b420b9dd134d86b537b01/lib/travis/build/bash/travis_setup_env.bash#L22 

This seems fine

**Comment by halcyondaz** [comment]
like this?

**Comment by halcyondaz** [comment]
im  new to git
next time it gets its own branch

**Comment by mikaelvesavuori** [comment]
Thanks for the find! Had a suggestion that I updated with the `tr` usage in your example.

I'd suggest the following as a solution. It checks for MacOS (because that's a bit particular) and otherwise assumes standard Linux functionality. At this point I'm not overly interested in Windows or anything, given where Bash is used most commonly.

```bash
daysSinceLastCommit() {
  last_commit_date=$(git log -1 --format="%ai")

  if [[ "$(uname | tr '[:upper:]' '[:lower:]')" == "darwin" ]]; then
    last_commit_timestamp=$(date -jf "%Y-%m-%d %H:%M:%S %z" "$last_commit_date" "+%s")
  else
    last_commit_timestamp=$(date -d "$last_commit_date" "+%s")
  fi

  current_timestamp=$(date "+%s")
  time_diff=$((current_timestamp - last_commit_timestamp))
  days_since_last_commit=$((time_diff / 86400)) # 86400 seconds in a day
  echo "Days since the last commit: $days_since_last_commit" >"$GITANALYZED_FOLDER/$FILENAME_DAYS_SINCE_LAST_COMMIT"
}
```

**Comment by halcyondaz** [comment]
yeah, seems good, should i change it?

**Comment by mikaelvesavuori** [comment]
Go ahead, and I'll merge.

**Comment by mikaelvesavuori** [comment]
Added the changes and merged.

**Pull request merged**
